receivers:
  otlp:
    protocols:
      http:  # HTTP receiver configuration
        endpoint: localhost:4318
      grpc:
        endpoint: localhost:4317

exporters:
  otlp/grpc:  # gRPC exporter configuration
    endpoint: "jaeger-agent:4317"
    tls:
      insecure: true  # For non-production environments

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: []
      exporters: [otlp/grpc]