receivers:
  otlp:
    protocols:
      http:  # HTTP receiver configuration
        endpoint: 0.0.0.0:4318
      grpc:
        endpoint: 0.0.0.0:4317

exporters:
  otlp:  # gRPC exporter configuration
    endpoint: "jaeger:4317"
    tls:
      insecure: true  # For non-production environments
  debug:
    verbosity: detailed

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [debug, otlp]